services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: clictec-front-client-nginx-proxy
    restart: always
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - proxy_red

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: clictec-front-client-letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL:-tuemail@clictec.es}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - proxy_red

  clictec-front-client:
    build:
      context: .
      dockerfile: clicTec-front-client.Dockerfile
    container_name: clictec-front-client
    restart: always
    expose:
      - "80"
    environment:
      API_UPSTREAM: ${API_UPSTREAM:-https://api.clictec.es}
      VIRTUAL_HOST: ${VIRTUAL_HOST:-clictec.es,www.clictec.es}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST:-clictec.es,www.clictec.es}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-tuemail@clictec.es}
    networks:
      - proxy_red

networks:
  proxy_red:
